print ("INFORMACION DEL PACIENTE")
paciente = input ("ingrese nombre y apellido del paciente: ")
fechaNacimiento = input ("ingrese la fecha de nacimiento del paciente: ")
print ("INFORMACION DE LA CLINICA")
direccionClinica = input ("ingrese la direccion de la clinica medica: ")
print ("INFORMACION DEL MEDICAMENTO")
nombreMedicamento = input ("ingrese el nombre del medicamento: ")
dosisMedicamento = input ("ingrese cantidad de dosis del medicamento: ")
usoMedicamento = input ("ingrese las instrucciones de uso del medicamento: ")
print ("NUEVO TURNO")
turnoNuevo = input ("ingrese la fecha del proximo turno: ")

print ("💉🩺RECETA MEDICA🩺💉")
print ("NOMBRE Y APELLIDO")
print (paciente)
print ("FACHA DE NACIMIENTO")
print (fechaNacimiento)
print ("LUGAR")
print (direccionClinica)
print ("MEDICAMENTO")
print (nombreMedicamento)
print ("CANTIDAD DE DOSIS")
print (dosisMedicamento)
print ("INSTRUCCIONES DE USO")
print (usoMedicamento)
print ("PROXIMO TURNO")
print (turnoNuevo)